[[firmware]]
id = "fredemmott"
title = "fredemmott/chromatic_dumper"
version = "v2026.09.20.0 (based on ModRetro v18.8)"
description = "ModRetro's firmware, modified to support FlashGBX."
filename_prefix = "fredemmott"
fpga_url = "https://github.com/fredemmott/chromatic_dumper/releases/download/dumper-v2026.09.27.00/evt1_x2.fs"
fpga_sha256 = "d4dd06ef87e2581b813cd556c4809ae7d4a44ab1842487a46f7cb56d427d67f3"

[[firmware]]
id = "modretro"
title = "ModRetro"
version = "v18.8"
description = "The original firmware for Chromatic."
fpga_url = "https://github.com/ModRetro/oss-chromatic-console-fpga/releases/download/v18.8/v18.8_20251224.fs"
fpga_sha256 = "7f5c7811d260f850dfba408178748a5c1aab803f7419bcb34adde70395a7a8af"
